name: Sync to Public Repo with Original Authors

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  sync-repos:
    if: ${{ github.repository == 'litz-lab/scarab_ll' && github.event_name == 'push' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Private Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure we have the full commit history

      - name: Configure Git (Keep Original Authors)
        run: |
          git config --global user.email "$(git log -1 --pretty=format:'%ae')"
          git config --global user.name "$(git log -1 --pretty=format:'%an')"

      - name: Force Authentication with Fine-Grained PAT
        env:
          PAT: ${{ secrets.SCARAB_SYNC_PAT }}
        run: |
          git remote remove public || true
          git remote add public https://${PAT}@github.com/litz-lab/scarab.git
          git credential reject https://github.com/  # Ensure old credentials are cleared

      - name: Debug PAT Authentication
        env:
	  PAT: ${{ secrets.SCARAB_SYNC_PAT }}
	run: |
	  echo "Testing authentication..."
	  curl -H "Authorization: Bearer $PAT" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/litz-lab/scarab

      - name: Push Updates to Public Repository
        env:
          PAT: ${{ secrets.SCARAB_SYNC_PAT }}
        run: |
	  git push https://${PAT}@github.com/litz-lab/scarab.git HEAD:main
